// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8Ke9ojQXQ_pfZ3aTXzbExUjrrv0K818',
    appId: '1:537416550673:ios:b1fc65a4028dd9d785a4b0',
    messagingSenderId: '537416550673',
    projectId: 'bhesab-6b24a',
    storageBucket: 'bhesab-6b24a.appspot.com',
    iosClientId: '537416550673-ks6v027u3bmtg1sl32hbqvlrijl1296p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhesab',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5__QH_EjiqnlT_KQeUkBmzOSM5sDENo',
    appId: '1:537416550673:web:e33a1a1cbca5d00985a4b0',
    messagingSenderId: '537416550673',
    projectId: 'bhesab-6b24a',
    authDomain: 'bhesab-6b24a.firebaseapp.com',
    storageBucket: 'bhesab-6b24a.appspot.com',
    measurementId: 'G-KBFC5BD76T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8Ke9ojQXQ_pfZ3aTXzbExUjrrv0K818',
    appId: '1:537416550673:ios:b1fc65a4028dd9d785a4b0',
    messagingSenderId: '537416550673',
    projectId: 'bhesab-6b24a',
    storageBucket: 'bhesab-6b24a.appspot.com',
    iosClientId: '537416550673-ks6v027u3bmtg1sl32hbqvlrijl1296p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhesab',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYh0AOcRcP4OQsO3JXbBWlt9f4KJK2Dk',
    appId: '1:537416550673:android:b750e396d73f5a4c85a4b0',
    messagingSenderId: '537416550673',
    projectId: 'bhesab-6b24a',
    storageBucket: 'bhesab-6b24a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5__QH_EjiqnlT_KQeUkBmzOSM5sDENo',
    appId: '1:537416550673:web:5e11ebda0641a6f385a4b0',
    messagingSenderId: '537416550673',
    projectId: 'bhesab-6b24a',
    authDomain: 'bhesab-6b24a.firebaseapp.com',
    storageBucket: 'bhesab-6b24a.appspot.com',
    measurementId: 'G-Y4ST598B55',
  );

}